name: gixat
description: "Garage Management System - Production SaaS."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.1.0
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^10.0.0
  font_awesome_flutter: ^10.12.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  graphql_flutter: ^5.2.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

dependency_overrides:
  characters: ^1.4.1
  connectivity_plus: ^7.0.0
  gql_dedupe_link: ^4.0.0
  matcher: ^0.12.18
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  normalize: ^0.10.0
  test_api: ^0.7.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
